[package]
name = "verify-component-adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
wasmparser = { workspace = true }
wat = { workspace = true }
anyhow = { workspace = true }
